
name: 'Snyk IaC Test Action'
inputs: 
  snyk-token:
    description: 'Token to use Snyk'
    required: true

  github-token: 
    description: 'Github token to comment on PR'
    required: true

  pr-number: 
    description: 'The number of the pull request'
    required: true

  snyk-severity: 
    description: 'The snky-severity'
    required: false
    default: 'high'

runs:
  using: 'composite' 
  steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: 'Check for .tf files'
      id: check_tf_files 
      shell: bash
      run: |

        if git ls-files '*.tf' | grep -q .; then
          echo "TERRAFORM_FILES_FOUND=true" >> $GITHUB_ENV
        else
          echo "TERRAFORM_FILES_FOUND=false" >> $GITHUB_ENV
        fi

    - name: Get .snyk file
      continue-on-error: true
      shell: bash
      run: |
        if aws s3api head-object --bucket snyk-iac-test --key ${{ github.event.repository.name }}/.snyk ; then
          mkdir snyk-ignore
          aws s3 cp s3://snyk-iac-test/${{ github.event.repository.name }}/.snyk ./snyk-ignore
          echo "Fetched .snyk ignore policy file for ${{ github.event.repository.name }}"
        else
          echo "No .snyk ignore policy file found"
        fi

    - name: Set up Python
      uses: actions/setup-python@v4 
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      with:
        python-version: '3.x'

    - name: 'Set up Node.js' 
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }} 
      uses: actions/setup-node@v4 
      with:
        node-version: '22.4.1'

    - name: Install Snyk CLI
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      shell: bash
      run: npm install -g snyk 

    - name: 'Authenticate Snyk CLI'
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      shell: bash
      env:
        SNYK_TOKEN: ${{inputs.snyk-token}} 
      run: snyk auth $SNYK_TOKEN

    - name: Run severity level script
      id: run-severity-script
      shell: bash
      run: |
        python ${GITHUB_ACTION_PATH}/scripts/severity_level.py ${{ inputs.snyk-severity }} > severity_result.txt
        SEVERITY_LEVEL=$(grep -oP 'SEVERITY_RESULT:\s*\K\S+' severity_result.txt)
        echo "SEVERITY_LEVEL=${SEVERITY_LEVEL}" >> $GITHUB_ENV

    - name: Get Snyk IaC Scan Full Report
      id: snyk-full-report
      shell: bash
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      run: |
        snyk iac test --severity-threshold=low > snyk_output.txt || true
        echo "Snyk test output:"
        cat snyk_output.txt
        
    - name: Add Snyk Iac Scan Full Report in the PR
      uses: actions/github-script@v6
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('snyk_output.txt', 'utf8');
          github.rest.issues.createComment({
            issue_number: ${{ inputs.pr-number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### Snyk Full Report:\n\`\`\`\n${output}\n\`\`\``
          });

    - name: Run Snyk Test
      shell: bash
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      run: |
        snyk iac test --severity-threshold=${{ env.SEVERITY_LEVEL }}